-- About Content tablosunu oluştur
CREATE TABLE AboutContents (
    Id int IDENTITY(1,1) PRIMARY KEY,
    Title nvarchar(100) NOT NULL,
    Subtitle nvarchar(200) NOT NULL,
    StoryTitle nvarchar(500) NOT NULL,
    StoryContent nvarchar(max) NOT NULL,
    StoryImageUrl nvarchar(500) NULL,
    MissionTitle nvarchar(500) NOT NULL,
    MissionContent nvarchar(max) NOT NULL,
    VisionTitle nvarchar(500) NOT NULL,
    VisionContent nvarchar(max) NOT NULL,
    ValuesTitle nvarchar(500) NULL,
    ValuesSubtitle nvarchar(500) NULL,
    ValueItems nvarchar(max) NULL,
    ProductionTitle nvarchar(500) NULL,
    ProductionSubtitle nvarchar(500) NULL,
    ProductionSteps nvarchar(max) NULL,
    CertificatesTitle nvarchar(500) NULL,
    CertificatesSubtitle nvarchar(500) NULL,
    CertificateItems nvarchar(max) NULL,
    RegionTitle nvarchar(500) NULL,
    RegionContent nvarchar(max) NULL,
    RegionImageUrl nvarchar(500) NULL,
    RegionFeatures nvarchar(max) NULL,
    CtaTitle nvarchar(500) NULL,
    CtaContent nvarchar(max) NULL,
    CtaButtonText nvarchar(200) NULL,
    CtaSecondButtonText nvarchar(200) NULL,
    StoryFeatures nvarchar(max) NULL,
    IsActive bit NOT NULL DEFAULT 1,
    CreatedAt datetime2 NOT NULL DEFAULT GETDATE(),
    UpdatedAt datetime2 NOT NULL DEFAULT GETDATE()
);

-- İlk varsayılan kaydı ekle
INSERT INTO AboutContents (
    Title, Subtitle, StoryTitle, StoryContent, StoryImageUrl,
    MissionTitle, MissionContent, VisionTitle, VisionContent,
    ValuesTitle, ValuesSubtitle,
    ValueItems,
    ProductionTitle, ProductionSubtitle,
    ProductionSteps,
    CertificatesTitle, CertificatesSubtitle,
    CertificateItems,
    RegionTitle, RegionContent, RegionImageUrl,
    RegionFeatures,
    CtaTitle, CtaContent, CtaButtonText, CtaSecondButtonText,
    StoryFeatures,
    IsActive, CreatedAt, UpdatedAt
) VALUES (
    N'Hakkımızda',
    N'Gelenekten geleceğe kaliteli lezzetlerin hikayesi',
    N'Hikayemiz',
    N'1985 yılında Balıkesir Bandırma''da başlayan yolculuğumuz, bugün Türkiye''nin dört bir yanına ulaşan kaliteli lezzetlerle devam ediyor. Dedemizden öğrendiğimiz geleneksel üretim yöntemlerini modern teknoloji ile birleştirerek, sofralarınıza en taze ve kaliteli süt ürünlerini sunuyoruz.',
    N'~/img/slider1-1920x750.jpeg',
    N'Misyonumuz',
    N'Geleneksel lezzetleri koruyarak, modern üretim standartları ile birleştirip, müşterilerimize en kaliteli süt ürünlerini sunmak. Her bir ürünümüzde Balıkesir''in bereketli topraklarının lezzetini yaşatmak.',
    N'Vizyonumuz',
    N'Türkiye''nin en güvenilir ve tercih edilen kaliteli süt ürünleri markası olmak. Geleneksel lezzetleri koruyarak, yeni nesillere aktarmak ve uluslararası pazarlarda da tanınan bir marka haline gelmek.',
    N'Değerlerimiz',
    N'Bizi biz yapan temel değerler',
    N'[{"Title":"Doğallık","Content":"Hiçbir katkı maddesi kullanmadan, tamamen doğal yöntemlerle üretim yapıyoruz.","Icon":"fas fa-leaf","Color":"success"},{"Title":"Kalite","Content":"En yüksek kalite standartlarında üretim yaparak müşteri memnuniyetini sağlıyoruz.","Icon":"fas fa-award","Color":"warning"},{"Title":"Gelenek","Content":"Nesillerden gelen geleneksel üretim yöntemlerini koruyor ve yaşatıyoruz.","Icon":"fas fa-history","Color":"primary"},{"Title":"Güven","Content":"Müşterilerimizin güvenini kazanmak ve sürdürmek en önemli önceliğimizdir.","Icon":"fas fa-heart","Color":"danger"}]',
    N'Üretim Sürecimiz',
    N'Kaliteli lezzetlerin yolculuğu',
    N'[{"StepNumber":1,"Title":"Süt Toplama","Content":"Balıkesir''in temiz havasında yetişen ineklerden günlük olarak taze süt toplanır."},{"StepNumber":2,"Title":"Kalite Kontrol","Content":"Toplanan sütler laboratuvar ortamında detaylı kalite kontrolünden geçirilir."},{"StepNumber":3,"Title":"Üretim","Content":"Geleneksel yöntemlerle modern teknoloji birleştirilerek üretim yapılır."},{"StepNumber":4,"Title":"Paketleme","Content":"Hijyenik koşullarda paketlenen ürünler soğuk zincirle teslim edilir."}]',
    N'Sertifikalarımız',
    N'Kalitemizin kanıtı',
    N'[{"Title":"ISO 22000","Description":"Gıda Güvenliği Yönetim Sistemi","Icon":"fas fa-certificate","Color":"primary"},{"Title":"HACCP","Description":"Tehlike Analizi ve Kritik Kontrol Noktaları","Icon":"fas fa-award","Color":"warning"},{"Title":"Helal Sertifikası","Description":"Helal Gıda Üretim Sertifikası","Icon":"fas fa-shield-alt","Color":"success"}]',
    N'Balıkesir Bandırma Bölgesi',
    N'Bandırma, Balıkesir''in bereketli topraklarında yer alan, doğal güzellikleri ve temiz havası ile ünlü bir bölgedir. Bölgenin zengin otlakları ve temiz su kaynakları, ineklerimizin en kaliteli sütü üretmesini sağlar.',
    N'~/img/slider2-1920x750.jpeg',
    N'[{"Title":"Balıkesir, Bandırma","Icon":"fas fa-map-marker-alt"},{"Title":"Mikro Klima","Icon":"fas fa-temperature-high"},{"Title":"Kaliteli Otlaklar","Icon":"fas fa-leaf"},{"Title":"Temiz Su Kaynakları","Icon":"fas fa-water"}]',
    N'Kaliteli Lezzetleri Keşfedin!',
    N'Balıkesir Bandırma''nın bereketli topraklarından sofralarınıza uzanan eşsiz lezzetleri deneyin.',
    N'Ürünlerimizi İnceleyin',
    N'Bize Ulaşın',
    N'[{"Title":"38 Yıllık Deneyim"},{"Title":"Kaliteli Üretim"},{"Title":"Geleneksel Yöntem"},{"Title":"Kalite Garantisi"}]',
    1,
    GETDATE(),
    GETDATE()
);

SELECT 'AboutContents tablosu başarıyla oluşturuldu ve varsayılan veri eklendi!' AS Result;
