-- SiteSettings tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SiteSettings' AND COLUMN_NAME = 'IsActive')
BEGIN
    ALTER TABLE SiteSettings ADD IsActive BIT NOT NULL DEFAULT 1;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SiteSettings' AND COLUMN_NAME = 'FaviconUrl')
BEGIN
    ALTER TABLE SiteSettings ADD FaviconUrl NVARCHAR(500) NULL DEFAULT '/favicon.ico';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SiteSettings' AND COLUMN_NAME = 'SiteKeywords')
BEGIN
    ALTER TABLE SiteSettings ADD SiteKeywords NVARCHAR(500) NULL DEFAULT 'süt, peynir, yoğurt, manyas, gıda';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SiteSettings' AND COLUMN_NAME = 'TwitterUrl')
BEGIN
    ALTER TABLE SiteSettings ADD TwitterUrl NVARCHAR(500) NULL DEFAULT '#';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SiteSettings' AND COLUMN_NAME = 'WorkingHours')
BEGIN
    ALTER TABLE SiteSettings ADD WorkingHours NVARCHAR(200) NULL DEFAULT 'Pzt-Cmt: 08:00-18:00';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SiteSettings' AND COLUMN_NAME = 'YoutubeUrl')
BEGIN
    ALTER TABLE SiteSettings ADD YoutubeUrl NVARCHAR(500) NULL DEFAULT '#';
END

-- CookieConsent tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CookieConsents' AND COLUMN_NAME = 'IsActive')
BEGIN
    ALTER TABLE CookieConsents ADD IsActive BIT NOT NULL DEFAULT 1;
END

-- CookieConsentDetail tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CookieConsentDetails' AND COLUMN_NAME = 'CreatedAt')
BEGIN
    ALTER TABLE CookieConsentDetails ADD CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE();
END

-- CookieCategory tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CookieCategories' AND COLUMN_NAME = 'SortOrder')
BEGIN
    ALTER TABLE CookieCategories ADD SortOrder INT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CookieCategories' AND COLUMN_NAME = 'CreatedAt')
BEGIN
    ALTER TABLE CookieCategories ADD CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE();
END

-- Products tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Products' AND COLUMN_NAME = 'IsActive')
BEGIN
    ALTER TABLE Products ADD IsActive BIT NOT NULL DEFAULT 1;
END

-- Categories tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Categories' AND COLUMN_NAME = 'IsActive')
BEGIN
    ALTER TABLE Categories ADD IsActive BIT NOT NULL DEFAULT 1;
END

-- Blog tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Blogs' AND COLUMN_NAME = 'IsActive')
BEGIN
    ALTER TABLE Blogs ADD IsActive BIT NOT NULL DEFAULT 1;
END

-- Gallery tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Galleries' AND COLUMN_NAME = 'IsActive')
BEGIN
    ALTER TABLE Galleries ADD IsActive BIT NOT NULL DEFAULT 1;
END



-- Video tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Videos' AND COLUMN_NAME = 'IsActive')
BEGIN
    ALTER TABLE Videos ADD IsActive BIT NOT NULL DEFAULT 1;
END

-- ContactMessage tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ContactMessages' AND COLUMN_NAME = 'IsActive')
BEGIN
    ALTER TABLE ContactMessages ADD IsActive BIT NOT NULL DEFAULT 1;
END

-- Expense tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Expenses' AND COLUMN_NAME = 'Date')
BEGIN
    ALTER TABLE Expenses ADD Date DATETIME2 NOT NULL DEFAULT GETDATE();
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Expenses' AND COLUMN_NAME = 'IsActive')
BEGIN
    ALTER TABLE Expenses ADD IsActive BIT NOT NULL DEFAULT 1;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Expenses' AND COLUMN_NAME = 'UpdatedAt')
BEGIN
    ALTER TABLE Expenses ADD UpdatedAt DATETIME2 NULL;
END

-- AboutContent tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AboutContents' AND COLUMN_NAME = 'Content')
BEGIN
    ALTER TABLE AboutContents ADD Content NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AboutContents' AND COLUMN_NAME = 'ImageUrl')
BEGIN
    ALTER TABLE AboutContents ADD ImageUrl NVARCHAR(500) NULL;
END

-- HomeContent tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HomeContents' AND COLUMN_NAME = 'Title')
BEGIN
    ALTER TABLE HomeContents ADD Title NVARCHAR(200) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HomeContents' AND COLUMN_NAME = 'Content')
BEGIN
    ALTER TABLE HomeContents ADD Content NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HomeContents' AND COLUMN_NAME = 'ImageUrl')
BEGIN
    ALTER TABLE HomeContents ADD ImageUrl NVARCHAR(500) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HomeContents' AND COLUMN_NAME = 'VideoUrl')
BEGIN
    ALTER TABLE HomeContents ADD VideoUrl NVARCHAR(500) NULL;
END

-- Cart tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Carts' AND COLUMN_NAME = 'CartItems')
BEGIN
    -- CartItems navigation property için foreign key kontrolü
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CartItems' AND COLUMN_NAME = 'CartId')
    BEGIN
        ALTER TABLE CartItems ADD CartId INT NULL;
        ALTER TABLE CartItems ADD CONSTRAINT FK_CartItems_Carts_CartId FOREIGN KEY (CartId) REFERENCES Carts(Id);
    END
END

-- CartItem tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CartItems' AND COLUMN_NAME = 'UnitPrice')
BEGIN
    ALTER TABLE CartItems ADD UnitPrice DECIMAL(18,2) NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CartItems' AND COLUMN_NAME = 'TotalPrice')
BEGIN
    ALTER TABLE CartItems ADD TotalPrice DECIMAL(18,2) NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CartItems' AND COLUMN_NAME = 'AddedAt')
BEGIN
    ALTER TABLE CartItems ADD AddedAt DATETIME2 NOT NULL DEFAULT GETDATE();
END

-- Order tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'CustomerName')
BEGIN
    ALTER TABLE Orders ADD CustomerName NVARCHAR(200) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'CustomerEmail')
BEGIN
    ALTER TABLE Orders ADD CustomerEmail NVARCHAR(200) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'CustomerPhone')
BEGIN
    ALTER TABLE Orders ADD CustomerPhone NVARCHAR(20) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'ShippingAddress')
BEGIN
    ALTER TABLE Orders ADD ShippingAddress NVARCHAR(500) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'City')
BEGIN
    ALTER TABLE Orders ADD City NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'PostalCode')
BEGIN
    ALTER TABLE Orders ADD PostalCode NVARCHAR(10) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'SubTotal')
BEGIN
    ALTER TABLE Orders ADD SubTotal DECIMAL(18,2) NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'DiscountAmount')
BEGIN
    ALTER TABLE Orders ADD DiscountAmount DECIMAL(18,2) NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'ShippingCost')
BEGIN
    ALTER TABLE Orders ADD ShippingCost DECIMAL(18,2) NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'TaxAmount')
BEGIN
    ALTER TABLE Orders ADD TaxAmount DECIMAL(18,2) NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'OrderStatus')
BEGIN
    ALTER TABLE Orders ADD OrderStatus NVARCHAR(50) NOT NULL DEFAULT 'Pending';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'PaymentStatus')
BEGIN
    ALTER TABLE Orders ADD PaymentStatus NVARCHAR(50) NOT NULL DEFAULT 'Pending';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'Notes')
BEGIN
    ALTER TABLE Orders ADD Notes NVARCHAR(1000) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'ShippedDate')
BEGIN
    ALTER TABLE Orders ADD ShippedDate DATETIME2 NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'DeliveredDate')
BEGIN
    ALTER TABLE Orders ADD DeliveredDate DATETIME2 NULL;
END

-- OrderItem tablosuna eksik kolonları ekle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'OrderItems' AND COLUMN_NAME = 'ProductName')
BEGIN
    ALTER TABLE OrderItems ADD ProductName NVARCHAR(200) NULL;
END

-- Eğer Status kolonu varsa ve OrderStatus/PaymentStatus yoksa, Status'u kaldır
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Orders' AND COLUMN_NAME = 'Status')
BEGIN
    ALTER TABLE Orders DROP COLUMN Status;
END

-- Eğer ExpenseDate kolonu varsa ve Date yoksa, ExpenseDate'i Date olarak yeniden adlandır
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Expenses' AND COLUMN_NAME = 'ExpenseDate')
    AND NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Expenses' AND COLUMN_NAME = 'Date')
BEGIN
    EXEC sp_rename 'Expenses.ExpenseDate', 'Date', 'COLUMN';
END

PRINT 'Database schema updated successfully!';
